[package]
name = "ns-emu-mod-downloader"
version = "0.2.1"
edition = "2024"
description = "A command-line tool for downloading mods for Switch emulators"
repository = "https://github.com/exefer/ns-emu-mod-downloader"
license = "GPL-3.0-or-later"
publish = false

[dependencies]
anyhow = "1.0.100"
curl = "0.4.49"
dirs = "6.0.0"
rayon = "1.11.0"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"

[profile.release]
opt-level = "s"
strip = true
lto = true
panic = "abort"
codegen-units = 1
